---
title: "EDA"
author: "Renjie Wei"
date: '2022-05-03'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
dt= read.csv("./hurrican703.csv")
ggplot(data=dt, aes(x = Longitude, y = Latitude)) + 
  stat_summary_2d(data = dt, aes(x = Longitude, y = Latitude, z = dt$Wind.kt), fun = median, binwidth = c(1, 1), show.legend = TRUE)
library(data.table)
dt <- as.data.table(dt)
summary(dt)
```

```{r}
library(tidyverse)
dt_long <- dt %>%
    dplyr::group_by(ID) %>% 
    mutate(Wind_prev = lag(Wind.kt, 1),
           Lat_change = Latitude - lag(Latitude, 1),
           Long_change = Longitude - lag(Longitude, 1),
           Wind_prev_prev = lag(Wind.kt, 2)) %>% 
    mutate(Wind_change = Wind_prev - Wind_prev_prev)

save(dt_long, file = "dt_long.RData")
```

```{r}
# Month and count
month = c("January", "April", "May", "June", "July", "August", "September", "October", "November", "December")

storms_month_name = distinct(group_by(select(dt_long, Month, ID), Month))

storms_month_name %>% 
  dplyr::group_by(Month) %>% 
  mutate(Month =  factor(Month, levels = month)) %>% 
  arrange(Month) %>% 
  ggplot(aes(x = Month)) +
  geom_bar()

dt_long %>% 
  dplyr::group_by(Month) %>% 
  mutate(avg_speed = mean(Wind.kt)) %>% 
  distinct(Month, avg_speed) %>% 
  mutate(Month =  factor(Month, levels = month)) %>% 
  arrange(Month) %>% 
  ggplot(aes(x = Month, y = avg_speed)) +
  geom_point()


# Season and count
storms_season_name = distinct(group_by(select(dt_long, Season, ID), Season))
ggplot(data = storms_season_name) + 
  geom_bar(aes(x = Season))

dt_long %>% 
  dplyr::group_by(Season) %>% 
  mutate(avg_speed = mean(Wind.kt)) %>% 
  distinct(Season, avg_speed) %>% 
  ggplot(aes(x = Season, y = avg_speed)) +
  geom_point() +
  geom_smooth(method = "loess")


# Nature and count
storms_nature_name = distinct(group_by(select(dt_long, Nature, ID), Nature))
ggplot(data = storms_nature_name) + 
  geom_bar(aes(x = Nature))

dt_long %>% 
  dplyr::group_by(Nature) %>% 
  mutate(avg_speed = mean(Wind.kt)) %>% 
  distinct(Nature, avg_speed) %>% 
  ggplot(aes(x = Nature, y = avg_speed)) +
  geom_point()
```



