---
title: "MCMC_result_summary"
author: "Renjie Wei"
date: '2022-05-06'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
load("MCMC.res.2.RData")
load("MCMC.res.bad.RData")
```

```{r ols_try}
load("dt_train.RData")
load("dt_test.RData")
#ols.beta.res = NULL
#for(i in 1:length(dt_train)){
#    lm.mdl = lm(Wind.kt~ Wind_prev+ Lat_change+ Long_change+ Wind_change, data = dt_train[[i]])
#    ols.beta.res = rbind(ols.beta.res, coef(lm.mdl))
#}
#
#par(mfrow = c(1, 5))
#hist(ols.beta.res[,1])
#hist(ols.beta.res[,2])
#hist(ols.beta.res[,3])
#hist(ols.beta.res[,4])
#hist(ols.beta.res[,5])
```



```{r extract_beta_sigma}
beta.res.plot = NULL
for (i in 1:10000) {
    B.res = MCMC.res.2$B[[i]]
    B.res = as.data.frame(B.res)
    B.res = colMeans(B.res, na.rm = T)
    beta.res.plot = rbind(beta.res.plot, B.res)
}

sigma.res.plot = NULL
for (i in 1:10000) {
    sigma.res = MCMC.res.2$sigma2[[i]]
    sigma.res = as.data.frame(sigma.res)
    sigma.res.plot = rbind(sigma.res.plot, sigma.res)
}

mu.res.plot = list(
    intercept = 1,
    Wind_prev = 2,
    Lat_change = 3,
    Long_change = 4,
    Wind_change = 5
)
for (i in 2:10000) {
    mu.res = MCMC.res.2$muvec[[i]]
    mu.res = as.data.frame(t(mu.res))
    mu.res.plot = rbind(mu.res.plot, mu.res)
}

```
```{r}
beta.res.plot.bad = NULL
for (i in 1:10000) {
    B.res = MCMC.res.bad$B[[i]]
    B.res = as.data.frame(B.res)
    B.res = colMeans(B.res, na.rm = T)
    beta.res.plot.bad = rbind(beta.res.plot.bad, B.res)
}

sigma.res.plot.bad = NULL
for (i in 1:10000) {
    sigma.res = MCMC.res.bad$sigma2[[i]]
    sigma.res = as.data.frame(sigma.res)
    sigma.res.plot.bad = rbind(sigma.res.plot.bad, sigma.res)
}

mu.res.plot.bad = list(
    intercept = 349,
    Wind_prev = 1046,
    Lat_change = 1743,
    Long_change = 2440,
    Wind_change = 3137
)
for (i in 2:10000) {
    mu.res = MCMC.res.bad$muvec[[i]]
    mu.res = as.data.frame(t(mu.res))
    mu.res.plot.bad = rbind(mu.res.plot.bad, mu.res)
}
```



```{r plot_mc_chain}
jpeg(file="./plots/mcmc_trace.jpg", width = 3200, height = 1800, quality = 100)
par(mfrow = c(2, 5))
plot(beta.res.plot[,1],type = "l", main = bquote("Trace plot of "~ beta[0]), ylab = bquote(beta[0]))
abline(v = 5001, col = 2, lty = 4)
plot(beta.res.plot[,2],type = "l", main = bquote("Trace plot of "~ beta[1]), ylab = bquote(beta[1]))
abline(v = 5001, col = 2, lty = 4)
plot(beta.res.plot[,3],type = "l", main = bquote("Trace plot of "~ beta[2]), ylab = bquote(beta[2]))
abline(v = 5001, col = 2, lty = 4)
plot(beta.res.plot[,4],type = "l", main = bquote("Trace plot of "~ beta[3]), ylab = bquote(beta[3]))
abline(v = 5001, col = 2, lty = 4)
plot(beta.res.plot[,5],type = "l", main = bquote("Trace plot of "~ beta[4]), ylab = bquote(beta[4]))
abline(v = 5001, col = 2, lty = 4)
#plot(sigma.res.plot[,1],type = "l", main = "Trace plot of sigma2")
plot(mu.res.plot[,1],type = "l", main = bquote("Trace plot of "~ mu[0]), ylab = bquote(mu[0]))
abline(v = 5001, col = 2, lty = 4)
plot(mu.res.plot[,2],type = "l", main = bquote("Trace plot of "~ mu[1]), ylab = bquote(mu[1]))
abline(v = 5001, col = 2, lty = 4)
plot(mu.res.plot[,3],type = "l", main = bquote("Trace plot of "~ mu[2]), ylab = bquote(mu[2]))
abline(v = 5001, col = 2, lty = 4)
plot(mu.res.plot[,4],type = "l", main = bquote("Trace plot of "~ mu[3]), ylab = bquote(mu[3]))
abline(v = 5001, col = 2, lty = 4)
plot(mu.res.plot[,5],type = "l", main = bquote("Trace plot of "~ mu[4]), ylab = bquote(mu[4]))
abline(v = 5001, col = 2, lty = 4)
dev.off()


jpeg(file="./plots/mcmc_hist.jpg", width = 3200, height = 1800, quality = 100)
par(mfrow = c(2, 5))
hist(beta.res.plot[5001:10000,1], main = bquote("Histogram plot of "~beta[0]),breaks = 80, xlab = bquote(beta[0]))
hist(beta.res.plot[5001:10000,2], main = bquote("Histogram plot of "~beta[1]),breaks = 80, xlab = bquote(beta[1]))
hist(beta.res.plot[5001:10000,3], main = bquote("Histogram plot of "~beta[2]),breaks = 80, xlab = bquote(beta[2]))
hist(beta.res.plot[5001:10000,4], main = bquote("Histogram plot of "~beta[3]),breaks = 80, xlab = bquote(beta[3]))
hist(beta.res.plot[5001:10000,5], main = bquote("Histogram plot of "~beta[4]),breaks = 80, xlab = bquote(beta[4]))
#hist(sigma.res.plot[,1], main = "Histogram plot of sigma2")
hist(mu.res.plot[5001:10000,1], main = bquote("Histogram plot of "~mu[0]), breaks = 80, xlab = bquote(mu[0]))
hist(mu.res.plot[5001:10000,2], main = bquote("Histogram plot of "~mu[1]), breaks = 80, xlab = bquote(mu[1]))
hist(mu.res.plot[5001:10000,3], main = bquote("Histogram plot of "~mu[2]), breaks = 80, xlab = bquote(mu[2]))
hist(mu.res.plot[5001:10000,4], main = bquote("Histogram plot of "~mu[3]), breaks = 80, xlab = bquote(mu[3]))
hist(mu.res.plot[5001:10000,5], main = bquote("Histogram plot of "~mu[4]), breaks = 80, xlab = bquote(mu[4]))
dev.off()
```

```{r bad_plots}
par(mfrow = c(2, 5))
plot(beta.res.plot.bad[,1],type = "l", main = bquote("Trace plot of "~ beta[0]), ylab = bquote(beta[0]))
abline(v = 5001, col = 2, lty = 4)
plot(beta.res.plot.bad[,2],type = "l", main = bquote("Trace plot of "~ beta[1]), ylab = bquote(beta[1]))
abline(v = 5001, col = 2, lty = 4)
plot(beta.res.plot.bad[,3],type = "l", main = bquote("Trace plot of "~ beta[2]), ylab = bquote(beta[2]))
abline(v = 5001, col = 2, lty = 4)
plot(beta.res.plot.bad[,4],type = "l", main = bquote("Trace plot of "~ beta[3]), ylab = bquote(beta[3]))
abline(v = 5001, col = 2, lty = 4)
plot(beta.res.plot.bad[,5],type = "l", main = bquote("Trace plot of "~ beta[4]), ylab = bquote(beta[4]))
abline(v = 5001, col = 2, lty = 4)
#plot(sigma.res.plot[,1],type = "l", main = "Trace plot of sigma2")
plot(mu.res.plot.bad[,1],type = "l", main = bquote("Trace plot of "~ mu[0]), ylab = bquote(mu[0]))
abline(v = 5001, col = 2, lty = 4)
plot(mu.res.plot.bad[,2],type = "l", main = bquote("Trace plot of "~ mu[1]), ylab = bquote(mu[1]))
abline(v = 5001, col = 2, lty = 4)
plot(mu.res.plot.bad[,3],type = "l", main = bquote("Trace plot of "~ mu[2]), ylab = bquote(mu[2]))
abline(v = 5001, col = 2, lty = 4)
plot(mu.res.plot.bad[,4],type = "l", main = bquote("Trace plot of "~ mu[3]), ylab = bquote(mu[3]))
abline(v = 5001, col = 2, lty = 4)
plot(mu.res.plot.bad[,5],type = "l", main = bquote("Trace plot of "~ mu[4]), ylab = bquote(mu[4]))
abline(v = 5001, col = 2, lty = 4)



par(mfrow = c(2, 5))
hist(beta.res.plot.bad[5001:10000,1], main = bquote("Histogram plot of "~beta[0]),breaks = 80, xlab = bquote(beta[0]))
hist(beta.res.plot.bad[5001:10000,2], main = bquote("Histogram plot of "~beta[1]),breaks = 80, xlab = bquote(beta[1]))
hist(beta.res.plot.bad[5001:10000,3], main = bquote("Histogram plot of "~beta[2]),breaks = 80, xlab = bquote(beta[2]))
hist(beta.res.plot.bad[5001:10000,4], main = bquote("Histogram plot of "~beta[3]),breaks = 80, xlab = bquote(beta[3]))
hist(beta.res.plot.bad[5001:10000,5], main = bquote("Histogram plot of "~beta[4]),breaks = 80, xlab = bquote(beta[4]))
#hist(sigma.res.plot[,1], main = "Histogram plot of sigma2")
hist(mu.res.plot.bad[5001:10000,1], main = bquote("Histogram plot of "~mu[0]), breaks = 80, xlab = bquote(mu[0]))
hist(mu.res.plot.bad[5001:10000,2], main = bquote("Histogram plot of "~mu[1]), breaks = 80, xlab = bquote(mu[1]))
hist(mu.res.plot.bad[5001:10000,3], main = bquote("Histogram plot of "~mu[2]), breaks = 80, xlab = bquote(mu[2]))
hist(mu.res.plot.bad[5001:10000,4], main = bquote("Histogram plot of "~mu[3]), breaks = 80, xlab = bquote(mu[3]))
hist(mu.res.plot.bad[5001:10000,5], main = bquote("Histogram plot of "~mu[4]), breaks = 80, xlab = bquote(mu[4]))

```


```{r tidy_df}
beta.plot.df = beta.res.plot %>% as_tibble() %>% 
    mutate(iter = seq(1:10000), type = "beta") %>% 
    rename(intercept = `(Intercept)`)
mu.plot.df = mu.res.plot %>% as_tibble() %>% 
    mutate(iter = seq(1:10000), type = "mu")
plot.df = rbind(beta.plot.df, mu.plot.df)
```
```{r tidy_plots}
library(ggplot2)
plot.df %>% pivot_longer(1:5, names_to = "varname", values_to = "value") %>% 
    ggplot(aes(x = iter, y = value, group = type, color = varname)) + 
    geom_line() + 
    facet_grid(type~varname, scales = "free", space = "free")
    
```


```{r}
# sample param inference
var.beta0 = var(beta.res.plot[5001:10000,1])
var.beta1 = var(beta.res.plot[5001:10000,2])
var.beta2 = var(beta.res.plot[5001:10000,3])
var.beta3 = var(beta.res.plot[5001:10000,4])
var.beta4 = var(beta.res.plot[5001:10000,5])
```

```{r}
# population param inference
var.mu0 =var(mu.res.plot[5001:10000,1])
var.mu1 =var(mu.res.plot[5001:10000,2])
var.mu2 =var(mu.res.plot[5001:10000,3])
var.mu3 =var(mu.res.plot[5001:10000,4])
var.mu4 =var(mu.res.plot[5001:10000,5])
```


```{r}
# sample param inference
var.beta0.bad = var(beta.res.plot.bad[5001:10000,1])
var.beta1.bad = var(beta.res.plot.bad[5001:10000,2])
var.beta2.bad = var(beta.res.plot.bad[5001:10000,3])
var.beta3.bad = var(beta.res.plot.bad[5001:10000,4])
var.beta4.bad = var(beta.res.plot.bad[5001:10000,5])
```

```{r}
# population param inference
var.mu0.bad =var(mu.res.plot.bad[5001:10000,1])
var.mu1.bad =var(mu.res.plot.bad[5001:10000,2])
var.mu2.bad =var(mu.res.plot.bad[5001:10000,3])
var.mu3.bad =var(mu.res.plot.bad[5001:10000,4])
var.mu4.bad =var(mu.res.plot.bad[5001:10000,5])
```

```{r extract_each_beta}
# use posterior mean of beta as our final Bayesian model coefficients

beta.res.post = matrix(rep(0,694*5), 694, 5)
for (i in 5001:10000) {
    B.res = MCMC.res.2$B[[i]]
    B.res = as.data.frame(B.res)
    beta.res.post = beta.res.post + B.res
}

beta.res.postmean = beta.res.post/ 5000
```

```{r}
load("ID_in.RData")
```

```{r append_id}
dt_train_id = NULL
dt_test_id = NULL
for (i in 1:length(dt_train)){
    temp_train = dt_train[[i]]
    temp_test = dt_test[[i]]
    temp_train$ID = ID_in[[i]]
    temp_test$ID = ID_in[[i]]
    dt_train_id = rbind(dt_train_id, temp_train)
    dt_test_id = rbind(dt_test_id, temp_test)
}
save(dt_train_id, file = "dt_train_id.RData")
save(dt_test_id, file = "dt_test_id.RData")

beta.res.postmean$ID = ID_in
row.names(beta.res.postmean) = NULL
save(beta.res.postmean, file = "beta.res.postmean.RData")
```


```{r summary_param_tab}
param_summary = tibble(
    variable_name = names(beta.res.postmean[1:5]),
    mean_beta = colMeans(beta.res.postmean[,1:5]),
    var_beta = c(var.beta0, var.beta1, var.beta2, var.beta3, var.beta4),
    ci_beta_lower = mean_beta + qnorm(.025)*sqrt(var_beta),
    ci_beta_upper = mean_beta + qnorm(.975)*sqrt(var_beta),
    mu = colMeans(mu.res.plot),
    var_mu = c(var.mu0, var.mu1, var.mu2, var.mu3, var.mu4),
    ci_mu_lower = mu + qnorm(.025)*sqrt(var_mu),
    ci_mu_upper = mu + qnorm(.975)*sqrt(var_mu),
)
save(param_summary, file = "param_summary.RData")
```

```{r summary_param_sigmas}
#dev.off()
#plot(sigma.res.plot[,1],type = "l", main = bquote("Trace plot of "~ sigma^2), ylab = bquote(sigma^2))
#abline(v = 5001, col = 2, lty = 4)

#plot(sigma.res.plot.bad[5001:10000,1],type = "l", main = bquote("Trace plot of "~ sigma^2), ylab = bquote(sigma^2))

Sigma.res.plot = NULL
for (i in 1:10000) {
    Sigma.res = MCMC.res.2$Sigma[[i]]
    Sigma.res = as.data.frame(t(Sigma.res[lower.tri(Sigma.res, diag = T)]))
    Sigma.res.plot = rbind(Sigma.res.plot, Sigma.res)
}


par(mfrow = c(4, 4))
plot(Sigma.res.plot[,1],type = "l", main = bquote("Trace plot of "~ Sigma[11]), ylab = bquote(Sigma[11]))
plot(Sigma.res.plot[,2],type = "l", main = bquote("Trace plot of "~ Sigma[12]), ylab = bquote(Sigma[12]))
plot(Sigma.res.plot[,3],type = "l", main = bquote("Trace plot of "~ Sigma[13]), ylab = bquote(Sigma[13]))
plot(Sigma.res.plot[,4],type = "l", main = bquote("Trace plot of "~ Sigma[14]), ylab = bquote(Sigma[14]))
plot(Sigma.res.plot[,5],type = "l", main = bquote("Trace plot of "~ Sigma[15]), ylab = bquote(Sigma[15]))
plot(Sigma.res.plot[,6],type = "l", main = bquote("Trace plot of "~ Sigma[22]), ylab = bquote(Sigma[22]))
plot(Sigma.res.plot[,7],type = "l", main = bquote("Trace plot of "~ Sigma[23]), ylab = bquote(Sigma[23]))
plot(Sigma.res.plot[,8],type = "l", main = bquote("Trace plot of "~ Sigma[24]), ylab = bquote(Sigma[24]))
plot(Sigma.res.plot[,9],type = "l", main = bquote("Trace plot of "~ Sigma[25]), ylab = bquote(Sigma[25]))
plot(Sigma.res.plot[,10],type = "l", main = bquote("Trace plot of "~ Sigma[33]), ylab = bquote(Sigma[33]))
plot(Sigma.res.plot[,11],type = "l", main = bquote("Trace plot of "~ Sigma[34]), ylab = bquote(Sigma[34]))
plot(Sigma.res.plot[,12],type = "l", main = bquote("Trace plot of "~ Sigma[35]), ylab = bquote(Sigma[35]))
plot(Sigma.res.plot[,13],type = "l", main = bquote("Trace plot of "~ Sigma[44]), ylab = bquote(Sigma[44]))
plot(Sigma.res.plot[,14],type = "l", main = bquote("Trace plot of "~ Sigma[45]), ylab = bquote(Sigma[45]))
plot(Sigma.res.plot[,15],type = "l", main = bquote("Trace plot of "~ Sigma[55]), ylab = bquote(Sigma[55]))
plot(sigma.res.plot[,1],type = "l", main = bquote("Trace plot of "~ sigma^2), ylab = bquote(sigma^2))


par(mfrow = c(4, 4))
hist(Sigma.res.plot[5001:10000,1], main = bquote("Histogram of "~ Sigma[11]), xlab = bquote(Sigma[11]))
hist(Sigma.res.plot[5001:10000,2], main = bquote("Histogram of "~ Sigma[12]), xlab = bquote(Sigma[12]))
hist(Sigma.res.plot[5001:10000,3], main = bquote("Histogram of "~ Sigma[13]), xlab = bquote(Sigma[13]))
hist(Sigma.res.plot[5001:10000,4], main = bquote("Histogram of "~ Sigma[14]), xlab = bquote(Sigma[14]))
hist(Sigma.res.plot[5001:10000,5], main = bquote("Histogram of "~ Sigma[15]), xlab = bquote(Sigma[15]))
hist(Sigma.res.plot[5001:10000,6], main = bquote("Histogram of "~ Sigma[22]), xlab = bquote(Sigma[22]))
hist(Sigma.res.plot[5001:10000,7], main = bquote("Histogram of "~ Sigma[23]), xlab = bquote(Sigma[23]))
hist(Sigma.res.plot[5001:10000,8], main = bquote("Histogram of "~ Sigma[24]), xlab = bquote(Sigma[24]))
hist(Sigma.res.plot[5001:10000,9], main = bquote("Histogram of "~ Sigma[25]), xlab = bquote(Sigma[25]))
hist(Sigma.res.plot[5001:10000,10], main = bquote("Histogram of "~ Sigma[33]), xlab = bquote(Sigma[33]))
hist(Sigma.res.plot[5001:10000,11], main = bquote("Histogram of "~ Sigma[34]), xlab = bquote(Sigma[34]))
hist(Sigma.res.plot[5001:10000,12], main = bquote("Histogram of "~ Sigma[35]), xlab = bquote(Sigma[35]))
hist(Sigma.res.plot[5001:10000,13], main = bquote("Histogram of "~ Sigma[44]), xlab = bquote(Sigma[44]))
hist(Sigma.res.plot[5001:10000,14], main = bquote("Histogram of "~ Sigma[45]), xlab = bquote(Sigma[45]))
hist(Sigma.res.plot[5001:10000,15], main = bquote("Histogram of "~ Sigma[55]), xlab = bquote(Sigma[55]))
hist(sigma.res.plot[5001:10000,1], main = bquote("Histogram of "~ sigma^2), xlab = bquote(sigma^2))

```

```{r sigma_summary}
sigma_summary = tibble(
    parameter = c(
        "$\\Sigma_{11}$",
        "$\\Sigma_{12}$",
        "$\\Sigma_{13}$",
        "$\\Sigma_{14}$",
        "$\\Sigma_{15}$",
        "$\\Sigma_{22}$",
        "$\\Sigma_{23}$",
        "$\\Sigma_{24}$",
        "$\\Sigma_{25}$",
        "$\\Sigma_{33}$",
        "$\\Sigma_{34}$",
        "$\\Sigma_{35}$",
        "$\\Sigma_{44}$",
        "$\\Sigma_{45}$",
        "$\\Sigma_{55}$",
        "$\\sigma^2$"
        ),
    estimates = c(colMeans(Sigma.res.plot[5001:10000,], na.rm = T),mean(sigma.res.plot[5001:10000,])),
    variance = c(sapply(Sigma.res.plot[5001:10000,], var), var(sigma.res.plot[5001:10000,])),
    CI_L = estimates + qnorm(.025)*sqrt(variance),
    CI_U = estimates + qnorm(.975)*sqrt(variance)
)
save(sigma_summary, file = "sigma_summary.RData")
```

```{r nse_batching}
b1 = colMeans(beta.res.plot[5001:6000,])
b2 = colMeans(beta.res.plot[6001:7000,])
b3 = colMeans(beta.res.plot[7001:8000,])
b4 = colMeans(beta.res.plot[8001:9000,])
b5 = colMeans(beta.res.plot[9001:10000,])

bbar = colMeans(beta.res.plot[5001:10000,])

nse.beta = sqrt(1/20*((b1-bbar)^2 + (b2-bbar)^2 + (b3-bbar)^2 + (b4-bbar)^2 + (b5-bbar)^2))


```

```{r}
s = c(sigma_summary$estimates[1:15])
Sig = matrix(NA, 5, 5)
Sig[lower.tri(Sig, diag = T)] = s
Sig[upper.tri(Sig)] <- t(Sig)[upper.tri(Sig)]
rou = cov2cor(Sig)
save(Sig, file = "./estimate_Sigma.RData")
save(rou, file = "./estimate_rou.RData")
```

```{r}
acf_mu0 = acf(mu.res.plot[,1], lag.max = 500)
acf_mu1 = acf(mu.res.plot[,2], lag.max = 500)
acf_mu2 = acf(mu.res.plot[,3], lag.max = 500)
acf_mu3 = acf(mu.res.plot[,4], lag.max = 500)
acf_mu4 = acf(mu.res.plot[,5], lag.max = 500)
acf_beta0 = acf(beta.res.plot[,1], lag.max = 500)
acf_beta1 = acf(beta.res.plot[,2], lag.max = 500)
acf_beta2 = acf(beta.res.plot[,3], lag.max = 500)
acf_beta3 = acf(beta.res.plot[,4], lag.max = 500)
acf_beta4 = acf(beta.res.plot[,5], lag.max = 500)

par(mfrow = c(2, 5))

plot(acf_mu0, main = bquote(mu[0]))
plot(acf_mu1, main = bquote(mu[1]))
plot(acf_mu2, main = bquote(mu[2]))
plot(acf_mu3, main = bquote(mu[3]))
plot(acf_mu4, main = bquote(mu[4]))
plot(acf_beta0, main = bquote(beta[0]))
plot(acf_beta1, main = bquote(beta[1]))
plot(acf_beta2, main = bquote(beta[2]))
plot(acf_beta3, main = bquote(beta[3]))
plot(acf_beta4, main = bquote(beta[4]))
```


```{r}
acf_Sigma1 = acf(Sigma.res.plot[5001:10000,1],lag.max = 500)
acf_Sigma2 = acf(Sigma.res.plot[5001:10000,2],lag.max = 500)
acf_Sigma3 = acf(Sigma.res.plot[5001:10000,3],lag.max = 500)
acf_Sigma4 = acf(Sigma.res.plot[5001:10000,4],lag.max = 500)
acf_Sigma5 = acf(Sigma.res.plot[5001:10000,5],lag.max = 500)
acf_Sigma6 = acf(Sigma.res.plot[5001:10000,6],lag.max = 500)
acf_Sigma7 = acf(Sigma.res.plot[5001:10000,7],lag.max = 500)
acf_Sigma8 = acf(Sigma.res.plot[5001:10000,8],lag.max = 500)
acf_Sigma9 = acf(Sigma.res.plot[5001:10000,9],lag.max = 500)
acf_Sigma10 = acf(Sigma.res.plot[5001:10000,10],lag.max = 500)
acf_Sigma11 = acf(Sigma.res.plot[5001:10000,11],lag.max = 500)
acf_Sigma12 = acf(Sigma.res.plot[5001:10000,12],lag.max = 500)
acf_Sigma13 = acf(Sigma.res.plot[5001:10000,13],lag.max = 500)
acf_Sigma14 = acf(Sigma.res.plot[5001:10000,14],lag.max = 500)
acf_Sigma15 = acf(Sigma.res.plot[5001:10000,15],lag.max = 500)
acf_sigma = acf(sigma.res.plot[5001:10000,],lag.max = 500)
par(mfrow = c(4, 4))
plot(acf_Sigma1 , main = bquote(Sigma[11]))
plot(acf_Sigma2 , main = bquote(Sigma[12]))
plot(acf_Sigma3 , main = bquote(Sigma[13]))
plot(acf_Sigma4 , main = bquote(Sigma[14]))
plot(acf_Sigma5 , main = bquote(Sigma[15]))
plot(acf_Sigma6 , main = bquote(Sigma[22]))
plot(acf_Sigma7 , main = bquote(Sigma[23]))
plot(acf_Sigma8 , main = bquote(Sigma[24]))
plot(acf_Sigma9 , main = bquote(Sigma[25]))
plot(acf_Sigma10, main = bquote(Sigma[33]))
plot(acf_Sigma11, main = bquote(Sigma[34]))
plot(acf_Sigma12, main = bquote(Sigma[35]))
plot(acf_Sigma13, main = bquote(Sigma[44]))
plot(acf_Sigma14, main = bquote(Sigma[45]))
plot(acf_Sigma15, main = bquote(Sigma[55]))
plot(acf_sigma, main = bquote(sigma^2))

dev.off()
```


