---
title: "model predict"
author: "Shengzhi Luo"
date: "05/05/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(MASS)
library(tidyverse)
library(dplyr)
library(Metrics)
library(gridExtra)
library(grid)
```

```{r,include=FALSE}
load("./dt_test_id.RData")
load("./beta.res.postmean.RData")
```

```{r}
beta.res.postmean = beta.res.postmean %>% rename(beta_0 = intercept, beta_1 = Wind_prev, beta_2 = Lat_change,  beta_3 = Long_change, beta_4 = Wind_change)

dt_res = merge(dt_test_id, beta.res.postmean, by = "ID")

dt_res = dt_res %>% 
  mutate(Wind_kt_pred = beta_0*intercept+beta_1*Wind_prev
         +beta_2*Lat_change+beta_3*Long_change+beta_4*Wind_change) %>%
  group_by(ID) %>% 
  mutate(r_square = 1-(sum((Wind_kt_pred-Wind.kt)^2))/(sum((Wind.kt-mean(Wind.kt))^2)),
         rmse = rmse(Wind.kt,Wind_kt_pred))
```

```{r}
  dt_rmse=
  dt_res %>% 
  dplyr::select(ID, r_square, rmse) %>% 
  distinct() %>% 
  mutate(r_square = round(r_square, 3),
         rmse = round(rmse,3)) %>% 
  filter(r_square > 0 && r_square < 1) %>% 
  arrange(rmse)
mean(dt_rmse$r_square)
mean(dt_rmse$rmse)
df = head(dt_rmse,10) 
save(dt_rmse, file = "./tables/dt_rmse.RData")
png("rmse.png",  height = 25*nrow(df), width = 100*ncol(df), bg = "white")
grid.table(df)
dev.off()
```

```{r}
hurricanes = read.csv("hurrican703.csv")
hurricanes_count = hurricanes %>% group_by(ID) %>% summarize(nobs = n()) %>% dplyr::select(c("ID","nobs"))
dt_rmse_plot = merge(hurricanes_count, dt_rmse,by = "ID") 
```

```{r}
dt_rmse[,1:2] %>% pivot_longer(r_square, names_to = "statistics", values_to = "value") %>% 
    ggplot(aes(y = value, group = statistics, col = statistics)) + geom_boxplot()

dt_rmse_plot %>% ggplot(aes(x = nobs, y = r_square, group = ID)) + geom_point()
```



```{r}
png("q4_prediction_plot.png", width = 2000, height = 1000)
dt_res %>% filter(ID %in% c( "CAMILLE.1969","AGNES.1972","IVAN.2004","SANDY.2012")) %>% 
  mutate(index = 1:n()) %>%
  ggplot(aes(y = Wind.kt, x = index))+
  geom_line(aes(color = "Actual Wind Speed"))+
  geom_line(aes(y = Wind_kt_pred, color = "Predicted Wind Speed"))+
  facet_wrap(.~ID, nrow = 2, scales = "free") +
  theme_classic()+
  labs(x = "Index",
       y = "Wind Speed",
       title = "Actual Wind Speed vs. Predicted Wind Speed")
dev.off()
```




