---
title: "Seasonal Difference Exploration"
author: "Hao Zheng (hz2770)"
date: "5/6/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(kableExtra)
```

## Explore the seasonal differences
```{r}
load("./dt_long.RData")
load("./ID_in.RData")
load("./beta.res.postmean.RData")

dt_season <-
  dt_long %>%
  drop_na() %>% 
  filter(ID %in% ID_in) %>% 
  distinct(ID, .keep_all = TRUE) %>% 
  select(ID, Season, Month, Nature) %>% 
  mutate(Month = factor(Month, levels = month.name))
```

```{r}
season_diff <- 
  merge(dt_season, beta.res.postmean, by = c("ID")) %>%
  janitor::clean_names()

# Beta0
intercept.fit <- lm(intercept ~ month + season + nature, data = season_diff)
# Beta1
wind_prev.fit <- lm(wind_prev ~ month + season + nature, data = season_diff)
# Beta2
lat_change.fit <- lm(lat_change ~ month + season + nature, data = season_diff)
# Beta3
long_change.fit <- lm(long_change ~ month + season + nature, data = season_diff)
#Beta4
wind_change.fit <- lm(wind_change ~ month + season + nature, data = season_diff)

summary(intercept.fit)
summary(wind_prev.fit)
summary(lat_change.fit)
summary(long_change.fit)
summary(wind_change.fit)
```

```{r, results = "asis"}
sum0 <- as.data.frame(summary(intercept.fit)$coefficients[,c(1,4)]) %>% rename(beta0.fit.Est = Estimate)
sum1 <- as.data.frame(summary(wind_prev.fit)$coefficients[,c(1,4)]) %>% rename(beta1.fit.Est = Estimate)
sum2 <- as.data.frame(summary(lat_change.fit)$coefficients[,c(1,4)]) %>% rename(beta2.fit.Est = Estimate)
sum3 <- as.data.frame(summary(long_change.fit)$coefficients[,c(1,4)]) %>% rename(beta3.fit.Est = Estimate)
sum4 <- as.data.frame(summary(wind_change.fit)$coefficients[,c(1,4)]) %>% rename(beta4.fit.Est = Estimate)

kable(cbind(sum0, sum1, sum2, sum3, sum4)) %>% 
  kable_paper()
```

```{r}
# Try to fit the beta model only with the variable season(which indicates the year)
# Beta0
intercept.fit.new <- lm(intercept ~ season, data = season_diff)
# Beta1
wind_prev.fit.new <- lm(wind_prev ~ season, data = season_diff)
# Beta2
lat_change.fit.new <- lm(lat_change ~ season, data = season_diff)
# Beta3
long_change.fit.new <- lm(long_change ~ season, data = season_diff)
#Beta4
wind_change.fit.new <- lm(wind_change ~ season, data = season_diff)

summary(intercept.fit.new)
summary(wind_prev.fit.new)
summary(lat_change.fit.new)
summary(long_change.fit.new)
summary(wind_change.fit.new)
```


## Some Visualizations
```{r}

```

